#!/bin/bash

echo " Enter salary "
read salary

if [[ $salary -le 30000 ]];
then 
	echo " 5% tax added "

elif [[ $salary -gt 30000 && $salary -lt 45000 ]];
then
	echo " 10% tax is added "

elif [[ $salary -gt 70000 ]]
then 
	echo " 15% tax is added "
else 
	echo "na"
fi
